version: '3.8'

services:
  # 1. MongoDB Service
  mongo:
    image: mongo:latest
    container_name: allocation_mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: smartuser
      MONGO_INITDB_ROOT_PASSWORD: smartpassword
      MONGO_INITDB_DATABASE: pm_internship_db
    restart: always

  # 2. FastAPI Backend API Service
  api:
    build: .
    container_name: smart_allocation_api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://smartuser:smartpassword@mongo:27017/pm_internship_db?authSource=admin
      SECRET_KEY: "SUPER_SECRET_KEY_FOR_JWT"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mongo_data:
